class AssignmentSubmissionModel {
  final String id;
  final String assignmentId;
  final String studentId;
  final String fileUrl;
  final DateTime submittedAt;
  final double? grade;

  // Joined fields
  final String? studentName;

  AssignmentSubmissionModel({
    required this.id,
    required this.assignmentId,
    required this.studentId,
    required this.fileUrl,
    required this.submittedAt,
    this.grade,
    this.studentName,
  });

  factory AssignmentSubmissionModel.fromJson(Map<String, dynamic> json) {
    return AssignmentSubmissionModel(
      id: json['id'] as String,
      assignmentId: json['assignment_id'] as String,
      studentId: json['student_id'] as String,
      fileUrl: json['file_url'] as String,
      submittedAt: DateTime.parse(json['submitted_at'] as String).toLocal(),
      grade: json['grade'] != null ? double.parse(json['grade'].toString()) : null,
      
      // Handle nested join for student context
      studentName: json['users'] != null ? json['users']['full_name'] : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'assignment_id': assignmentId,
      'student_id': studentId,
      'file_url': fileUrl,
      'grade': grade,
      // ID and submittedAt are generated by DB
    };
  }
}
